using System.Collections.Generic;
using UnityEngine;

namespace VNCScreen
{
    /// <summary>
    /// Translate from Unity Keycode to XK Code (from x11)
    /// </summary>
    public class KeyTranslator
    {
        public static Dictionary<KeyCode, uint> KeyDict = new Dictionary<KeyCode, uint>()
        {
            { KeyCode.None, 0 },
            { KeyCode.Delete, 0xffff },
            { KeyCode.Tab, 0xff09 },
            { KeyCode.Clear, 0xff0b },
            { KeyCode.Return, 0xff0D },
            { KeyCode.Pause, 0xff13 },
            { KeyCode.Escape, 0xff1B },
            { KeyCode.Space, 0x20 },
            { KeyCode.Keypad0, 0xffb0 },
            { KeyCode.Keypad1, 0xffb1 },
            { KeyCode.Keypad2, 0xffb2 },
            { KeyCode.Keypad3, 0xffb3 },
            { KeyCode.Keypad4, 0xffb4 },
            { KeyCode.Keypad5, 0xffb5 },
            { KeyCode.Keypad6, 0xffb6 },
            { KeyCode.Keypad7, 0xffb7 },
            { KeyCode.Keypad8, 0xffb8 },
            { KeyCode.Keypad9, 0xffb9 },
            { KeyCode.KeypadPeriod, 0xffac },
            { KeyCode.KeypadDivide, 0xffaf },
            { KeyCode.KeypadMultiply, 0xffaa },
            { KeyCode.KeypadMinus, 0xffad },
            { KeyCode.KeypadPlus, 0xffab },
            { KeyCode.KeypadEnter, 0xff8d },
            { KeyCode.UpArrow, 0xff52 },
            { KeyCode.DownArrow, 0xff54 },
            { KeyCode.RightArrow, 0xff53 },
            { KeyCode.LeftArrow, 0xff51 },
            { KeyCode.Insert, 0xff63 },
            { KeyCode.Home, 0xff50 },
            { KeyCode.End, 0xff57 },
            { KeyCode.PageUp, 0xff55 },
            { KeyCode.PageDown, 0xff56 },
            { KeyCode.F1, 0xffbe },
            { KeyCode.F2, 0xffbf },
            { KeyCode.F3, 0xffc0 },
            { KeyCode.F4, 0xffc1 },
            { KeyCode.F5, 0xffc2 },
            { KeyCode.F6, 0xffc3 },
            { KeyCode.F7, 0xffc4 },
            { KeyCode.F8, 0xffc5 },
            { KeyCode.F9, 0xffc6 },
            { KeyCode.F10, 0xffc7 },
            { KeyCode.F11, 0xffc8 },
            { KeyCode.F12, 0xffc9 },
            { KeyCode.F13, 0xffca },
            { KeyCode.F14, 0xffcb },
            { KeyCode.F15, 0xffcc },
            { KeyCode.Alpha0, 0x0030 },
            { KeyCode.Alpha1, 0x0031 },
            { KeyCode.Alpha2, 0x0032 },
            { KeyCode.Alpha3, 0x0033 },
            { KeyCode.Alpha4, 0x0034 },
            { KeyCode.Alpha5, 0x0035 },
            { KeyCode.Alpha6, 0x0036 },
            { KeyCode.Alpha7, 0x0037 },
            { KeyCode.Alpha8, 0x0038 },
            { KeyCode.Alpha9, 0x0039 },
            { KeyCode.Exclaim, 0x0021 },
            { KeyCode.DoubleQuote, 0x0022 },
            { KeyCode.Hash, 0x0023 },
            { KeyCode.Dollar, 0x0024 },
            { KeyCode.Ampersand, 0x0026 },
            { KeyCode.Quote, 0x0027 },
            { KeyCode.LeftParen, 0x0028 },
            { KeyCode.RightParen, 0x0029 },
            { KeyCode.Asterisk, 0x002a },
            { KeyCode.Plus, 0x002b },
            { KeyCode.Comma, 0x002c },
            { KeyCode.Minus, 0x002d },
            { KeyCode.Period, 0x002e },
            { KeyCode.Slash, 0x002f },

            { KeyCode.Colon, 0x003a },
            { KeyCode.Semicolon, 0x003b },
            { KeyCode.Less, 0x003c },
            { KeyCode.Equals, 0x003d },
            { KeyCode.Greater, 0x003e },
            { KeyCode.Question, 0x003f },
            { KeyCode.At, 0x0040 },
            { KeyCode.LeftBracket, 0x005b },
            { KeyCode.Backslash, 0x005c },
            { KeyCode.RightBracket, 0x005d },
            { KeyCode.Caret, 0x005e },
            { KeyCode.Underscore, 0x005f },
            { KeyCode.BackQuote, 0x0060 },
            { KeyCode.A, 0x0061 },
            { KeyCode.B, 0x0062 },
            { KeyCode.C, 0x0063 },
            { KeyCode.D, 0x0064 },
            { KeyCode.E, 0x0065 },
            { KeyCode.F, 0x0066 },
            { KeyCode.G, 0x0067 },
            { KeyCode.H, 0x0068 },
            { KeyCode.I, 0x0069 },
            { KeyCode.J, 0x006a },
            { KeyCode.K, 0x006b },
            { KeyCode.L, 0x006c },
            { KeyCode.M, 0x006d },
            { KeyCode.N, 0x006e },
            { KeyCode.O, 0x006f },
            { KeyCode.P, 0x0070 },
            { KeyCode.Q, 0x0071 },
            { KeyCode.R, 0x0072 },
            { KeyCode.S, 0x0073 },
            { KeyCode.T, 0x0074 },
            { KeyCode.U, 0x0075 },
            { KeyCode.V, 0x0076 },
            { KeyCode.W, 0x0077 },
            { KeyCode.X, 0x0078 },
            { KeyCode.Y, 0x0079 },
            { KeyCode.Z, 0x007a },
            { KeyCode.Numlock, 0xff7f },
            { KeyCode.CapsLock, 0xffe5 },
            { KeyCode.ScrollLock, 0xff14 },
            { KeyCode.RightShift, 0xffe2 },
            { KeyCode.LeftShift, 0xffe1 },
            { KeyCode.RightControl, 0xffe4 },
            { KeyCode.LeftControl, 0xffe3 },
            { KeyCode.RightAlt, 0xffea },
            { KeyCode.LeftAlt, 0xffe9 },
            { KeyCode.LeftCommand, 0xffe3 },
            { KeyCode.LeftWindows, 0xffe7 },
            { KeyCode.RightCommand, 0xffe4 }
        };
    }
}
